# -*- coding: utf-8 -*-
"""Phatnt_SE173285_Lab05_UnsupervisedLearning_Final - FIXED VERSION

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13awdj1YvuouYuGMi4XkBTmk_H3y3JEqe

# CÂU HỎI KHỞI ĐỘNG

**Q1: Nếu bạn là SOC analyst và nhận được 10 triệu log mỗi ngày, tại sao không thể dùng Supervised Learning để phát hiện tất cả mối đe dọa?**

* **Khó khăn trong việc gán nhãn (Labeling):** Học máy có giám sát đòi hỏi dữ liệu phải được gán nhãn "tấn công" hoặc "bình thường" bởi các chuyên gia. Việc gán nhãn thủ công cho 10 triệu log mỗi ngày là không thể thực hiện được do tốn quá nhiều thời gian, chi phí và nhân lực.
* **Sự bùng nổ của tấn công Zero-day:** Khoảng **91% các cuộc tấn công mạng** bắt đầu bằng các kỹ thuật chưa từng thấy trước đó (zero-day). Supervised Learning sẽ thất bại trong việc phát hiện những mối đe dọa này vì nó chỉ có thể nhận diện những gì đã được gán nhãn và học từ trước.
* **Dữ liệu không có nhãn chiếm đa số:** Trong môi trường thực tế, hơn **99% dữ liệu thu thập được là dữ liệu không có nhãn**. Nếu chỉ dùng Supervised Learning, chúng ta sẽ bỏ qua phần lớn lượng dữ liệu khổng lồ này, nơi ẩn chứa nhiều hành vi bất thường tiềm ẩn.
* **Mất cân bằng dữ liệu cực hạn:** Tỷ lệ tấn công thực tế thường cực thấp (có thể chỉ 0.01%) so với lưu lượng bình thường. Điều này khiến mô hình Supervised dễ bị thiên lệch, có xu hướng dự đoán mọi thứ là "bình thường" để đạt độ chính xác cao nhưng thực chất lại **bỏ sót các cuộc tấn công** (Nghịch lý độ chính xác - Accuracy Paradox).


**Q2: Sự khác biệt giữa Clustering và Anomaly Detection? Khi nào dùng mỗi loại?**

Mặc dù cả hai đều thuộc Học máy không giám sát, chúng có mục tiêu và ứng dụng khác nhau:

  + **Clustering (Phân cụm):**
    + **Bản chất:** Là kỹ thuật **nhóm các điểm dữ liệu tương đồng** lại với nhau dựa trên các đặc trưng hành vi mà không cần nhãn biết trước.
    + **Khi nào dùng:** Dùng khi bạn muốn khám phá cấu trúc ẩn của dữ liệu, ví dụ như **phân nhóm các họ mã độc** có hành vi giống nhau, loại bỏ các cảnh báo trùng lặp (deduplication) trong hệ thống SIEM, hoặc phân loại các nhóm người dùng/thiết bị có hành vi tương đồng.
  + **Anomaly Detection (Phát hiện bất thường):**
    + **Bản chất:** Là việc xác định các điểm dữ liệu lệch đáng kể so với hành vi bình thường (baseline) hoặc không thuộc về bất kỳ nhóm thông thường nào.
    + **Khi nào dùng:** Dùng để phát hiện những điều "chưa từng biết", ví dụ như **phát hiện tấn công zero-day**, mối đe dọa nội bộ (insider threats) hoặc các điểm ngoại lệ (outliers) thưa thớt trong hàng triệu luồng dữ liệu.

**Q3: Một kết nối mạng 'bất thường' nghĩa là gì? Cho 2 ví dụ cụ thể.**
Một kết nối mạng bất thường là kết nối có hành vi sai lệch so với các mẫu hành vi bình thường đã được thiết lập từ trước (baseline). D��ới đây là 2 ví dụ cụ thể:

1. **Trích xuất dữ liệu trái phép (Data Exfiltration)**: Một kết nối có lượng dữ liệu gửi đi từ nguồn (src_bytes) **lớn bất thường** và thời gian duy trì kết nối (duration) cực dài so với mức trung bình hàng ngày.Ví dụ: Một máy trạm bình thường chỉ gửi vài MB dữ liệu mỗi ngày nhưng đột ngột gửi đi hàng trăm MB dữ liệu ra ngoài internet trong nhiều giờ liên tục.

2. **Tấn công từ chối dịch vụ (DoS/SYN Flood):** Một nguồn gửi đi **hàng loạt yêu cầu kết nối trong thời gian rất ngắn** (count cao) nhưng tỷ lệ lỗi kết nối(serror_rate hoặc rerror_rate) lại cực cao (ví dụ: đạt mức 0.8 - 0.9) do các kết nối không được hoàn thành. Đây là dấu hiệu điển hình của việc kẻ tấn công đang cố gắng làm tê liệt hệ thống bằng cách gửi dồn dập các gói tin SYN.

# **Cell 1: Khởi tạo thư viện và đọc dữ liệu**

**Kêt quả cho ra được phân loại như sau:**

**Phân bổ nhãn (Labels):**

*   normal: 13,449 (khoảng 53.4%)
*   anomaly: 11,743 (khoảng 46.6%)

**Nhận xét:** Trong bài lab này, dữ liệu đã được tinh chỉnh để khá cân bằng. Tuy nhiên, cần lưu ý rằng trong môi trường an ninh mạng thực tế, tỷ lệ tấn công thường cực thấp (dưới 1% hoặc thậm chí 0.1%), dẫn đến hiện tượng Accuracy Paradox (nghịch lý độ chính xác)
"""

# Python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, normalize
from sklearn.cluster import KMeans, DBSCAN, MiniBatchKMeans
from sklearn.decomposition import PCA
from sklearn.ensemble import IsolationForest
from sklearn.metrics import (silhouette_score, adjusted_rand_score, 
                             classification_report, confusion_matrix, 
                             roc_auc_score, precision_score, recall_score, 
                             f1_score)
from scipy.spatial.distance import euclidean, cityblock, cosine
from sklearn.neighbors import NearestNeighbors
import warnings
warnings.filterwarnings('ignore')

print("=" * 80)
print("SE173285 - LAB 05: UNSUPERVISED LEARNING (FIXED VERSION)")
print("=" * 80)

# ============================================================================
# CELL 1: Import và đọc dữ liệu
# ============================================================================
print("\n[CELL 1] Loading dataset...")
df = pd.read_csv('nsl_kdd_binary.csv')
print(f'Dataset: {df.shape[0]} rows x {df.shape[1]} cols')
print("\nLabel distribution:")
print(df['label'].value_counts())

# ============================================================================
# CELL 2: Chuẩn bị features - FIX: Đúng mapping label
# ============================================================================
print("\n[CELL 2] Preparing features...")

# FIX 1: Map 'anomaly' thay vì 'attack'
df['label_num'] = df['label'].map({'normal': 0, 'anomaly': 1})
print(f"✓ Label mapping: normal->0, anomaly->1")

# Mã hóa categorical features
df_enc = pd.get_dummies(df, columns=['protocol_type', 'flag'])

# FIX 2: Gán label_num vào df_enc ngay
df_enc['label_num'] = df['label_num']
print(f"✓ label_num added to df_enc")

# Chọn subset features liên quan đến behavior
behavioral_features = [
    'duration', 'src_bytes', 'dst_bytes',
    'wrong_fragment', 'urgent', 'count',
    'srv_count', 'serror_rate', 'rerror_rate',
]

# Lọc chỉ lấy cột tồn tại trong dataset
available = [f for f in behavioral_features if f in df_enc.columns]
print(f'Features được dùng ({len(available)}): {available}')

X_raw = df_enc[available]
y_true = df_enc['label_num'].copy()

# Chuẩn hóa — BẮT BUỘC với K-Means
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_raw)
print('✓ Dữ liệu đã được chuẩn hóa')
print(f"✓ y_true shape: {y_true.shape}, unique values: {y_true.unique()}")

# ============================================================================
# CELL 3: Elbow Method & Silhouette Score
# ============================================================================
print("\n[CELL 3] Elbow Method & Silhouette Analysis...")

wcss_list = []
sil_list = []
K_range = range(2, 11)

for k in K_range:
    km = KMeans(n_clusters=k, init='k-means++', n_init=10, random_state=42)
    km.fit(X_scaled)
    wcss_list.append(km.inertia_)
    sil_list.append(silhouette_score(X_scaled, km.labels_, sample_size=3000))
    print(f'K={k}: WCSS={km.inertia_:.0f}, Silhouette={sil_list[-1]:.4f}')

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

# Elbow plot
ax1.plot(list(K_range), wcss_list, 'bo-', linewidth=2, markersize=8)
ax1.set_title('Elbow Method — WCSS vs K', fontsize=12)
ax1.set_xlabel('Số clusters (K)')
ax1.set_ylabel('WCSS (Inertia)')
ax1.axvline(x=5, color='red', linestyle='--', label='K=5 (gợi ý)')
ax1.legend()

# Silhouette plot
ax2.plot(list(K_range), sil_list, 'gs-', linewidth=2, markersize=8)
ax2.set_title('Silhouette Score vs K', fontsize=12)
ax2.set_xlabel('Số clusters (K)')
ax2.set_ylabel('Silhouette Score (cao hơn = tốt hơn)')

plt.tight_layout()
plt.savefig('elbow_silhouette.png', dpi=120)
plt.show()

# ============================================================================
# CELL 4: Huấn luyện K-Means
# ============================================================================
print("\n[CELL 4] Training K-Means...")

K_OPTIMAL = 5
kmeans = KMeans(n_clusters=K_OPTIMAL, init='k-means++',
                n_init=20, random_state=42)
kmeans.fit(X_scaled)

# Gán nhãn cluster vào dataframe
df_enc['cluster'] = kmeans.labels_

print(f'Silhouette Score (K={K_OPTIMAL}): {silhouette_score(X_scaled, kmeans.labels_):.4f}')
print('\nPhân bố mẫu trong từng cluster:')
print(df_enc['cluster'].value_counts().sort_index())

# ============================================================================
# CELL 5: Phân tích Cluster Profiling
# ============================================================================
print("\n[CELL 5] Cluster Profiling Analysis...")

print('====== PHÂN TÍCH CLUSTER ======')

# FIX 3: Tính toán attack % cho từng cluster
cluster_analysis = df_enc.groupby('cluster').agg(
    total=('label_num', 'count'),
    n_attack=('label_num', 'sum'),
).round(4)

cluster_analysis['pct_attack'] = (cluster_analysis['n_attack'] / cluster_analysis['total']).round(4)
cluster_analysis['pct_attack_pct'] = (cluster_analysis['pct_attack'] * 100).round(1)

print(cluster_analysis)

# Thống kê mean của từng feature per cluster
print('\nMean features per cluster:')
profile = df_enc.groupby('cluster')[available].mean().round(2)
print(profile.to_string())

# Visualization
fig, axes = plt.subplots(1, 2, figsize=(13, 5))

# Stacked bar: attack vs normal per cluster
ct = pd.crosstab(df_enc['cluster'], df_enc['label_num'])

# FIX 4: Đúng cách xử lý column names
if 0.0 in ct.columns and 1.0 in ct.columns:
    ct.columns = ['Normal', 'Anomaly']
elif 0.0 in ct.columns:
    ct = ct.rename(columns={0.0: 'Normal'})
    ct['Anomaly'] = 0
else:
    ct['Normal'] = 0
    ct['Anomaly'] = 0

ct.plot(kind='bar', stacked=True, color=['steelblue', 'firebrick'],
        edgecolor='white', ax=axes[0])
axes[0].set_title('Thành phần Anomaly/Normal trong mỗi Cluster')
axes[0].set_xlabel('Cluster ID')
axes[0].set_ylabel('Số lượng')
axes[0].tick_params(axis='x', rotation=0)

# % attack per cluster
cluster_analysis['pct_attack_pct'].plot(kind='bar', color='firebrick',
                                        edgecolor='black', ax=axes[1])
axes[1].set_title('% Anomaly trong mỗi Cluster')
axes[1].set_xlabel('Cluster ID')
axes[1].set_ylabel('% Anomaly')
axes[1].axhline(y=50, color='orange', linestyle='--', label='50% threshold')
axes[1].legend()
axes[1].tick_params(axis='x', rotation=0)

plt.tight_layout()
plt.savefig('cluster_analysis.png', dpi=120)
plt.show()

# ============================================================================
# CELL 6: K-Distance Plot cho DBSCAN
# ============================================================================
print("\n[CELL 6] K-Distance Plot for DBSCAN eps selection...")

# Dùng subset nhỏ hơn để tính nhanh
sample_idx = np.random.choice(len(X_scaled), min(5000, len(X_scaled)), replace=False)
X_sample = X_scaled[sample_idx]

# Tính khoảng cách đến 5 nearest neighbors
k_nn = 5
nbrs = NearestNeighbors(n_neighbors=k_nn).fit(X_sample)
distances, _ = nbrs.kneighbors(X_sample)

# Sắp xếp khoảng cách k-NN theo thứ tự tăng dần
k_distances = np.sort(distances[:, k_nn - 1])[::-1]

plt.figure(figsize=(8, 4))
plt.plot(k_distances, linewidth=1.5, color='steelblue')
plt.title(f'K-Distance Plot (k={k_nn}) — Tìm eps tối ưu', fontsize=12)
plt.xlabel('Điểm dữ liệu (sắp xếp theo khoảng cách giảm dần)')
plt.ylabel(f'Khoảng cách đến {k_nn}-NN')
plt.axhline(y=1.5, color='red', linestyle='--', label='eps thử = 1.5')
plt.axhline(y=2.0, color='orange', linestyle='--', label='eps thử = 2.0')
plt.legend()
plt.tight_layout()
plt.savefig('kdistance.png', dpi=120)
plt.show()
print('Quan sát: tìm điểm "khuỷu" — eps tại đó = tham số tốt nhất')

# ============================================================================
# CELL 7: DBSCAN với nhiều eps
# ============================================================================
print("\n[CELL 7] Testing DBSCAN with different eps values...")

eps_values = [0.8, 1.5, 2.5]

for eps in eps_values:
    dbscan = DBSCAN(eps=eps, min_samples=5, n_jobs=-1)
    db_labels = dbscan.fit_predict(X_scaled)

    n_clusters = len(set(db_labels)) - (1 if -1 in db_labels else 0)
    n_noise = np.sum(db_labels == -1)
    pct_noise = n_noise / len(db_labels) * 100

    # Tỷ lệ attack trong noise points
    noise_mask = db_labels == -1
    if n_noise > 0:
        attack_in_noise = y_true[noise_mask].mean() * 100
    else:
        attack_in_noise = 0

    print(f'eps={eps:.1f}: Clusters={n_clusters:3d}, Noise={n_noise:5d} '
          f'({pct_noise:.1f}%), Attack-in-noise={attack_in_noise:.1f}%')

# ============================================================================
# CELL 8: DBSCAN chi tiết
# ============================================================================
print("\n[CELL 8] Detailed DBSCAN Analysis...")

EPS_BEST = 1.5  # Điều chỉnh dựa trên K-Distance plot

dbscan_final = DBSCAN(eps=EPS_BEST, min_samples=5, n_jobs=-1)
db_labels_final = dbscan_final.fit_predict(X_scaled)
df_enc['dbscan_cluster'] = db_labels_final

n_clusters = len(set(db_labels_final)) - (1 if -1 in db_labels_final else 0)
noise_mask = db_labels_final == -1
n_noise = noise_mask.sum()

print(f'Số clusters: {n_clusters}')
print(f'Số noise points: {n_noise} ({n_noise/len(db_labels_final)*100:.2f}%)')
print()
print('--- Phân tích Noise Points ---')
noise_df = df_enc[noise_mask]
print(f'Total noise: {len(noise_df)}')
print(f'Anomaly trong noise: {noise_df["label_num"].sum()} ({noise_df["label_num"].mean()*100:.1f}%)')
print(f'Normal trong noise: {(1-noise_df["label_num"]).sum()} ({(1-noise_df["label_num"].mean())*100:.1f}%)')
print()
print('Profile trung bình của noise points:')
print(noise_df[available].mean().round(3))

# ============================================================================
# CELL 9: Visualization DBSCAN vs Ground Truth
# ============================================================================
print("\n[CELL 9] DBSCAN vs Ground Truth Visualization...")

fig, axes = plt.subplots(1, 2, figsize=(13, 5))

# FIX 5: Sử dụng X_scaled thay vì X_raw để visualization
for ax, (labels, title, cmap) in zip(axes, [
    (db_labels_final, f'DBSCAN (eps={EPS_BEST}, noise=đen)', 'tab10'),
    (y_true.values, 'Ground Truth (0=Normal, 1=Anomaly)', 'RdBu'),
]):
    sc = ax.scatter(
        X_scaled[:, 0], X_scaled[:, 1],
        c=labels, cmap=cmap, s=5, alpha=0.4
    )
    ax.set_title(title, fontsize=11)
    ax.set_xlabel(available[0] + ' (normalized)')
    ax.set_ylabel(available[1] + ' (normalized)')

plt.tight_layout()
plt.savefig('dbscan_vs_truth.png', dpi=120)
plt.show()

# ============================================================================
# CELL 10: Distance Metrics Comparison
# ============================================================================
print("\n[CELL 10] Distance Metrics Comparison...")

# 3 session network: [duration, src_bytes, dst_bytes, failed_logins, count]
session_normal = np.array([10.0, 500.0, 1200.0, 0.0, 10.0])
session_suspicious = np.array([12.0, 520.0, 1180.0, 0.0, 11.0])
session_attack = np.array([0.0, 5000.0, 0.0, 5.0, 100.0])

sessions = {
    'Normal vs Suspicious': (session_normal, session_suspicious),
    'Normal vs Attack': (session_normal, session_attack),
}

print(f'{"Pair":<26} {"Euclidean":>12} {"Manhattan":>12} {"Cosine":>10}')
print('-' * 65)
for name, (a, b) in sessions.items():
    print(f'{name:<26} {euclidean(a,b):>12.4f} {cityblock(a,b):>12.4f} {cosine(a,b):>10.4f}')

# ============================================================================
# CELL 11: K-Means với metric khác nhau
# ============================================================================
print("\n[CELL 11] K-Means with Different Metrics...")

results = {}

# FIX 6: Xử lý NaN và convert to int trước khi tính metrics
y_true_clean = y_true.dropna().astype(int)
non_nan_mask = y_true.notna()
X_scaled_filtered = X_scaled[non_nan_mask.values]

# Euclidean (chuẩn hóa) — K-Means mặc định
km_euc = MiniBatchKMeans(n_clusters=5, random_state=42, n_init=10)
km_euc.fit(X_scaled_filtered)
ari_euc = adjusted_rand_score(y_true_clean, km_euc.labels_)
results['Euclidean (scaled)'] = ari_euc

# Dùng cosine: normalize vector trước (cosine ~ euclidean sau L2 normalize)
X_l2_filtered = normalize(X_scaled_filtered, norm='l2')
km_cos = MiniBatchKMeans(n_clusters=5, random_state=42, n_init=10)
km_cos.fit(X_l2_filtered)
ari_cos = adjusted_rand_score(y_true_clean, km_cos.labels_)
results['Cosine (L2-norm)'] = ari_cos

print('ARI (Adjusted Rand Index) — cao hơn = cluster khớp label thật hơn:')
for metric, ari in results.items():
    print(f' {metric:<25}: ARI = {ari:.4f}')
print()
print('ARI = 1.0: hoàn hảo | ARI = 0.0: ngẫu nhiên | ARI < 0: tệ hơn ngẫu nhiên')

# ============================================================================
# CELL 12: PCA - Scree Plot
# ============================================================================
print("\n[CELL 12] PCA - Scree Plot Analysis...")

# FIX 7: Xử lý cách chọn columns đúng
cols_to_drop = [c for c in ['label', 'label_num', 'cluster', 'dbscan_cluster'] 
                if c in df_enc.columns]
X_full = df_enc.drop(cols_to_drop, axis=1)
X_full = X_full.select_dtypes(include=[np.number]).fillna(0)

print(f'Số features đầy đủ: {X_full.shape[1]}')

scaler_full = StandardScaler()
X_full_scaled = scaler_full.fit_transform(X_full)

# Fit PCA với tất cả components
pca_full = PCA(random_state=42)
pca_full.fit(X_full_scaled)

# Cumulative explained variance
cum_var = np.cumsum(pca_full.explained_variance_ratio_)
n_95 = np.argmax(cum_var >= 0.95) + 1
n_99 = np.argmax(cum_var >= 0.99) + 1

print(f'PC cần để giữ 95% variance: {n_95}')
print(f'PC cần để giữ 99% variance: {n_99}')
print(f'Giảm từ {X_full.shape[1]} → {n_95} features (tiết kiệm {(1-n_95/X_full.shape[1])*100:.0f}%)')

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

# Individual variance
ax1.bar(range(1, min(21, X_full.shape[1]+1)),
        pca_full.explained_variance_ratio_[:20] * 100,
        color='steelblue', edgecolor='navy')
ax1.set_title('Variance được giải thích bởi từng PC (Top 20)')
ax1.set_xlabel('Principal Component')
ax1.set_ylabel('Explained Variance (%)')

# Cumulative variance
ax2.plot(range(1, len(cum_var)+1), cum_var * 100, 'b-o', markersize=4)
ax2.axhline(y=95, color='red', linestyle='--', label='95% threshold')
ax2.axhline(y=99, color='orange', linestyle='--', label='99% threshold')
ax2.axvline(x=n_95, color='red', linestyle=':')
ax2.set_title('Cumulative Explained Variance')
ax2.set_xlabel('Số Principal Components')
ax2.set_ylabel('Cumulative Variance (%)')
ax2.legend()
ax2.set_xlim(1, min(50, X_full.shape[1]))

plt.tight_layout()
plt.savefig('pca_scree.png', dpi=120)
plt.show()

# ============================================================================
# CELL 13: PCA 2D Visualization
# ============================================================================
print("\n[CELL 13] PCA 2D Visualization...")

pca_2d = PCA(n_components=2, random_state=42)
X_2d = pca_2d.fit_transform(X_full_scaled)

print(f'Variance PC1: {pca_2d.explained_variance_ratio_[0]*100:.1f}%')
print(f'Variance PC2: {pca_2d.explained_variance_ratio_[1]*100:.1f}%')
print(f'Tổng: {sum(pca_2d.explained_variance_ratio_)*100:.1f}%')

fig, axes = plt.subplots(1, 3, figsize=(16, 5))

# Plot 1: Ground Truth
for label, color, name in [(0, 'steelblue', 'Normal'), (1, 'firebrick', 'Anomaly')]:
    mask = y_true == label
    axes[0].scatter(X_2d[mask, 0], X_2d[mask, 1],
                    c=color, s=5, alpha=0.35, label=name)
axes[0].set_title('Ground Truth Labels', fontsize=11)
axes[0].set_xlabel(f'PC1 ({pca_2d.explained_variance_ratio_[0]*100:.1f}%)')
axes[0].set_ylabel(f'PC2 ({pca_2d.explained_variance_ratio_[1]*100:.1f}%)')
axes[0].legend(markerscale=3)

# Plot 2: K-Means clusters
scatter2 = axes[1].scatter(X_2d[:, 0], X_2d[:, 1],
                           c=df_enc['cluster'], cmap='tab10', s=5, alpha=0.35)
axes[1].set_title(f'K-Means Clusters (K={K_OPTIMAL})', fontsize=11)
axes[1].set_xlabel(f'PC1 ({pca_2d.explained_variance_ratio_[0]*100:.1f}%)')
axes[1].set_ylabel(f'PC2 ({pca_2d.explained_variance_ratio_[1]*100:.1f}%)')

# Plot 3: DBSCAN (noise = đen)
db_plot_labels = df_enc['dbscan_cluster'].values
colors_db = ['black' if l == -1 else plt.cm.tab10(l % 10) for l in db_plot_labels]
axes[2].scatter(X_2d[:, 0], X_2d[:, 1], c=colors_db, s=5, alpha=0.3)
axes[2].set_title(f'DBSCAN (đen = noise/anomaly)', fontsize=11)
axes[2].set_xlabel(f'PC1 ({pca_2d.explained_variance_ratio_[0]*100:.1f}%)')
axes[2].set_ylabel(f'PC2 ({pca_2d.explained_variance_ratio_[1]*100:.1f}%)')

plt.tight_layout()
plt.savefig('pca_visualization.png', dpi=120)
plt.show()

# ============================================================================
# CELL 14: PCA Loadings
# ============================================================================
print("\n[CELL 14] PCA Loadings Analysis...")

feature_names = X_full.columns
loadings = pd.DataFrame(
    pca_2d.components_.T,
    index=feature_names,
    columns=['PC1', 'PC2']
)

print('Top 8 features đóng góp vào PC1 (absolute loading):')
print(loadings['PC1'].abs().sort_values(ascending=False).head(8).round(4))
print()
print('Top 8 features đóng góp vào PC2 (absolute loading):')
print(loadings['PC2'].abs().sort_values(ascending=False).head(8).round(4))

# Visualize loadings
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
for ax, pc in zip(axes, ['PC1', 'PC2']):
    top_features = loadings[pc].abs().sort_values(ascending=False).head(10)
    top_features.plot(kind='barh', ax=ax, color='steelblue', edgecolor='black')
    ax.set_title(f'Top features trong {pc}')
    ax.invert_yaxis()
plt.tight_layout()
plt.savefig('pca_loadings.png', dpi=120)
plt.show()

# ============================================================================
# CELL 15: Isolation Forest Training
# ============================================================================
print("\n[CELL 15] Training Isolation Forest...")

iso_forest = IsolationForest(
    n_estimators=200,
    contamination=0.1,  # Ước tính 10% là anomaly
    random_state=42,
    n_jobs=-1
)

iso_forest.fit(X_full_scaled)

# Dự đoán: +1 = normal, -1 = anomaly
iso_pred = iso_forest.predict(X_full_scaled)
iso_scores = iso_forest.score_samples(X_full_scaled)

# Chuyển sang: 1 = anomaly, 0 = normal (khớp convention IDS)
iso_anomaly = (iso_pred == -1).astype(int)

print(f'Số anomaly phát hiện: {iso_anomaly.sum()} ({iso_anomaly.mean()*100:.1f}%)')
print(f'Số normal: {(iso_anomaly==0).sum()} ({(iso_anomaly==0).mean()*100:.1f}%)')

# ============================================================================
# CELL 16: Đánh giá Isolation Forest
# ============================================================================
print("\n[CELL 16] Isolation Forest Evaluation...")

# FIX 8: Xử lý NaN trước tính metrics
y_true_eval = y_true.dropna().astype(int)
non_nan_mask_eval = y_true.notna()
iso_anomaly_eval = iso_anomaly[non_nan_mask_eval.values]
iso_scores_eval = iso_scores[non_nan_mask_eval.values]
X_2d_eval = X_2d[non_nan_mask_eval.values]

print('====== ISOLATION FOREST — ĐÁNH GIÁ ======')
print(classification_report(y_true_eval, iso_anomaly_eval,
                            target_names=['Normal (0)', 'Anomaly (1)']))

# FIX 9: Tính ROC-AUC đúng cách (dùng decision_function thay vì score_samples)
# decision_function = -score_samples
iso_decision = -iso_scores_eval
try:
    roc_auc = roc_auc_score(y_true_eval, iso_decision)
    print(f'ROC-AUC Score: {roc_auc:.4f}')
    print('(ROC-AUC = 1.0: hoàn hảo | 0.5: ngẫu nhiên | > 0.7: chấp nhận được)')
except:
    print('ROC-AUC Score: Không thể tính (một hoặc cả hai lớp không có mẫu)')

# Plotting score distribution and PCA 2D
fig, axes = plt.subplots(1, 2, figsize=(13, 5))

# Histogram anomaly scores
ax = axes[0]
ax.hist(iso_scores_eval[y_true_eval == 0], bins=60, alpha=0.6,
        color='steelblue', label='Normal', density=True)
ax.hist(iso_scores_eval[y_true_eval == 1], bins=60, alpha=0.6,
        color='firebrick', label='Anomaly', density=True)

# FIX 10: Tính threshold từ percentile thay vì iso_forest.offset_
threshold = np.percentile(iso_scores_eval, 10)
ax.axvline(x=threshold, color='black', linestyle='--',
           linewidth=2, label=f'Threshold={threshold:.3f}')
ax.set_title('Phân phối Anomaly Score', fontsize=11)
ax.set_xlabel('Isolation Score (thấp hơn = anomaly hơn)')
ax.set_ylabel('Density')
ax.legend()

# Scatter: PCA 2D tô màu bằng anomaly score
sc = axes[1].scatter(
    X_2d_eval[:, 0], X_2d_eval[:, 1],
    c=-iso_scores_eval, cmap='RdYlGn_r',
    s=5, alpha=0.5
)
plt.colorbar(sc, ax=axes[1], label='Anomaly Score (cao = bất thường)')
axes[1].set_title('Anomaly Score trong không gian PCA 2D', fontsize=11)
axes[1].set_xlabel('PC1')
axes[1].set_ylabel('PC2')

plt.tight_layout()
plt.savefig('isolation_forest.png', dpi=120)
plt.show()

# ============================================================================
# CELL 18: Tuning Contamination
# ============================================================================
print("\n[CELL 18] Tuning Contamination Parameter...")

print(f'{"Contamination":>15} {"Precision":>12} {"Recall":>10} {"F1":>8} {"# Alerts":>10}')
print('-' * 60)

contaminations = []
precisions = []
recalls = []
f1_scores_list = []
num_alerts = []

for cont in [0.05, 0.10, 0.15, 0.20, 0.30]:
    iso = IsolationForest(n_estimators=200, contamination=cont, random_state=42)
    iso.fit(X_full_scaled)
    pred = (iso.predict(X_full_scaled) == -1).astype(int)

    # FIX 11: Xử lý NaN trước tính metrics
    y_true_filtered_tune = y_true.dropna().astype(int)
    pred_filtered_tune = pred[y_true.notna().values]

    p = precision_score(y_true_filtered_tune, pred_filtered_tune, zero_division=0)
    r = recall_score(y_true_filtered_tune, pred_filtered_tune, zero_division=0)
    f = f1_score(y_true_filtered_tune, pred_filtered_tune, zero_division=0)
    n = pred_filtered_tune.sum()

    print(f'{cont:>15.2f} {p:>12.4f} {r:>10.4f} {f:>8.4f} {n:>10}')

    contaminations.append(cont)
    precisions.append(p)
    recalls.append(r)
    f1_scores_list.append(f)
    num_alerts.append(n)

print()
print('Trade-off: contamination cao → Recall tăng, Precision giảm (nhiều False Positive)')

# Plotting the results
fig, ax1 = plt.subplots(figsize=(10, 6))

ax1.set_xlabel('Contamination')
ax1.set_ylabel('Metric Score', color='tab:blue')
ax1.plot(contaminations, precisions, label='Precision', marker='o', color='tab:blue')
ax1.plot(contaminations, recalls, label='Recall', marker='x', color='tab:green')
ax1.plot(contaminations, f1_scores_list, label='F1-Score', marker='s', color='tab:red')
ax1.tick_params(axis='y', labelcolor='tab:blue')
ax1.legend(loc='upper left')
ax1.grid(True, linestyle='--', alpha=0.7)

ax2 = ax1.twinx()
ax2.set_ylabel('# Alerts', color='tab:purple')
ax2.plot(contaminations, num_alerts, label='# Alerts', marker='D', linestyle='--', color='tab:purple', alpha=0.6)
ax2.tick_params(axis='y', labelcolor='tab:purple')
ax2.legend(loc='upper right')

fig.tight_layout()
plt.title('Isolation Forest: Performance vs. Contamination')
plt.savefig('contamination_tuning.png', dpi=120)
plt.show()

# ============================================================================
# CELL 19: Comparison of All Methods
# ============================================================================
print("\n[CELL 19] Comparison of All Unsupervised Methods...")

# K-Means: dùng cluster có % attack cao nhất làm 'positive prediction'
top_attack_cluster = cluster_analysis['pct_attack'].idxmax()
kmeans_pred = (df_enc['cluster'] == top_attack_cluster).astype(int)

# DBSCAN: noise = anomaly = attack
dbscan_pred = (df_enc['dbscan_cluster'] == -1).astype(int)

methods = {
    'K-Means (best cluster)': kmeans_pred,
    'DBSCAN (noise=attack)': dbscan_pred,
    'Isolation Forest': iso_anomaly,
}

comparison_results = []

print(f'{"Method":<28} {"Precision":>11} {"Recall":>9} {"F1":>7} {"#Alerts":>9}')
print('-' * 70)

for name, pred in methods.items():
    # FIX 12: Xử lý NaN trước tính metrics
    y_true_filtered_compare = y_true.dropna().astype(int)
    pred_filtered_compare = pred[y_true.notna().values]

    p = precision_score(y_true_filtered_compare, pred_filtered_compare, zero_division=0)
    r = recall_score(y_true_filtered_compare, pred_filtered_compare, zero_division=0)
    f = f1_score(y_true_filtered_compare, pred_filtered_compare, zero_division=0)
    n = pred_filtered_compare.sum()
    print(f'{name:<28} {p:>11.4f} {r:>9.4f} {f:>7.4f} {n:>9}')
    comparison_results.append({'Method': name, 'Precision': p, 'Recall': r, 'F1': f, '#Alerts': n})

# Convert results to DataFrame for easier plotting
results_df = pd.DataFrame(comparison_results)
results_df.set_index('Method', inplace=True)

# Plotting the comparison
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Plot 1: Precision, Recall, F1-Score
metrics_to_plot = ['Precision', 'Recall', 'F1']
results_df[metrics_to_plot].plot(kind='bar', ax=axes[0], colormap='viridis', width=0.8)
axes[0].set_title('So sánh các chỉ số hiệu suất (P, R, F1)', fontsize=14)
axes[0].set_ylabel('Điểm số', fontsize=12)
axes[0].set_xlabel('Phương pháp', fontsize=12)
axes[0].tick_params(axis='x', rotation=45)
axes[0].legend(title='Metric')
axes[0].grid(axis='y', linestyle='--', alpha=0.7)

# Plot 2: Number of Alerts
results_df['#Alerts'].plot(kind='bar', ax=axes[1], color='coral', width=0.6)
axes[1].set_title('Số lượng cảnh báo được phát hiện', fontsize=14)
axes[1].set_ylabel('Số cảnh báo', fontsize=12)
axes[1].set_xlabel('Phương pháp', fontsize=12)
axes[1].tick_params(axis='x', rotation=45)
axes[1].grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()
plt.savefig('unsupervised_comparison.png', dpi=120)
plt.show()

print("\n" + "=" * 80)
print("✓ LAB 05 COMPLETED SUCCESSFULLY")
print("=" * 80)
